[package]
name = "crowdfunding_contract"
type = "contract"
authors = ["Satyam Bansal <satyamsgsits1994@gmail.com>"]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.2", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.2", directory = "noir-projects/aztec-nr/uint-note" }
router = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.2", directory = "noir-projects/noir-contracts/contracts/protocol/router_contract" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.2", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
